# name: code coverage
# on: [push]
# jobs:
#   code-coverage-tests:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: "14"
#       - run: node -v
#       - run: yarn -v
#       - run: yarn install
#       - run: yarn create:jwtkeys
#       - run: yarn test:codecov
#       - run: bash <(curl -s https://codecov.io/bash) # Upload to Codecov
